### ISSUE TITLE
Running kubescape on clusters yaml produces "empty list of workloads"

### ISSUE THREAD

**Issue by JDemler** [armosec/kubescape#288]
While `kubescape scan framework nsa` works as expected getting the clusters yaml first and then running it through kubescape produces `empty list of workloads - no workloads found`:

```
$ kubectl get all -o yaml --all-namespaces | kubescape scan framework nsa -
ARMO security scanner starting
[progress] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
empty list of workloads - no workloads found
```

**Comment by dwertent** [comment]
This issue is because the object returned from kubectl is of kind `List` while kubescape does not support that kind.

I fixed the issue in our [dev branch](https://github.com/armosec/kubescape/blob/dev/resourcehandler/filesloader.go#L217) this should be supported next release. 

Thank you @JDemler  for finding the issue.

FYI, I do not recommend scanning a cluster this way. Normally when scanning a cluster, Kubescape removes duplications of resources e.g. when testing whether a deployment contains a hostPath, the Kubescape will test only the deployment by filtering out the replicasets and pods so the risk-score is not effected from the same miss configurations. But when you pass the resources as input file/stdin, kubescape does not filter out anything so the same resource is tested more than once.

e.g.
Testing "Allowed hostPath" control on cluster:
![image](https://user-images.githubusercontent.com/64066841/147653242-49d69671-2d84-43d3-af55-44101ac5ae5f.png)

Testing "Allowed hostPath" control on stdin input:
![image](https://user-images.githubusercontent.com/64066841/147653284-fcb1231e-ea7d-4ce3-98d6-0e3f5cdfc668.png)

**Comment by JDemler** [comment]
Works as expected! Thank you @dwertent for this fast fix!
