### ISSUE TITLE
Data export and publishing cluster or YAML scan results on UI

### ISSUE THREAD

**Issue by sprathod369** [armosec/kubescape#290]
It's great to have released the user-friendly UI as part of kubescape and I'm trying to explore this functionality. I've 2 questions
1) Please let me know on what specific data (or metadata) get exported out from the local environment as part of running the scan & publishing the vulnerability results on UI? Any sensitive data gets exported as part of using --submit=true & --account parameters that users need to be cognizant of?

2) Post signing up on the armo cloud, I tried to scan my static k8s yaml file using the following command.
$ kubescape scan framework nsa *.yaml --submit --account=xyz
The command runs successfully and I see results on stdout but at the end there are no errors or confirmation that results have been pushed to https://portal.armo.cloud/risk. 

I'm unable to see any results on the UI dashboard.
Is there anything I'm missing in terms of yaml scan to see the results on UI? Is it supported as of today and if not do we plan to in near future?

Thanks

**Comment by dwertent** [comment]
Thank you @sprathod369 for asking this questions, evidently this two points are not clarified enough.

1. Kubescape removes any sensitive data before submitting ([implementation](https://github.com/armosec/kubescape/blob/3fad2f3430cd9cabb468b6f67999779a85e9eda5/opaprocessor/processorhandlerutils.go#L109)). We consider sensitive data:
    - Field `data` in kind `Secret`
    - Field `data` in kind `ConfigMap`
    - Container environments variables values
2. The SaaS UI is designed for scanning cluster and not static k8s yaml files, for this reason we do not support submitting the scan results in such case. The reason is that the SaaS UI was originally developed for tracking results over time, and when you scan yaml files there is no consistency because you can scan different files every time.
We are working on a way of grouping scan results of yaml files and then we will enable the `submit` functionality also for yaml files

**Comment by sprathod369** [comment]
Thank you @dwertent - appreciate your inputs. It helps!!

**Comment by slashben** [comment]
> It's great to have released the user-friendly UI as part of kubescape and I'm trying to explore this functionality. I've 2 questions
> 
> 1. Please let me know on what specific data (or metadata) get exported out from the local environment as part of running the scan & publishing the vulnerability results on UI? Any sensitive data gets exported as part of using --submit=true & --account parameters that users need to be cognizant of?
> 2. Post signing up on the armo cloud, I tried to scan my static k8s yaml file using the following command.
>    $ kubescape scan framework nsa *.yaml --submit --account=xyz
>    The command runs successfully and I see results on stdout but at the end there are no errors or confirmation that results have been pushed to https://portal.armo.cloud/risk.
> 
> I'm unable to see any results on the UI dashboard. Is there anything I'm missing in terms of yaml scan to see the results on UI? Is it supported as of today and if not do we plan to in near future?
> 
> Thanks

@sprathod369 , we have put the UI support for YAML scanning on the development pipe, so you will have it soon :) We are looking for users to validate our design for this feature. Would you be ready to discuss one on one?
