### ISSUE TITLE
flipping fail threshold is a breaking change

### ISSUE THREAD

**Issue by clintmod** [armosec/kubescape#297]
If I have a pipeline with -f currently set to 100 to fail if any check fails it will silently never fail if I upgrade.

You should create a new name for the flag or rev up to 2.0 with a breaking change notice.

**Comment by slashben** [comment]
Hi @clintmod , you are right. This is a breaking change. Let me explain what happened.

We have developed Kubescape with a very specific risk score calculation in our mind. The formula is designed to give you a ratio of what is wrong in your cluster vs what could go wrong. 

Before we released the Kubescape in August/September we saw that the risk score calculation did not work good enough and dropped it. Instead, we calculated the proportion of failed resources vs all resources. We thought we had time to solve the risk calculation. We did not expect this fast and wide adoption of Kubescape... :-)

We did fix the risk score calculation in the last month and did release. Since it is a risk score, it uses hight values for higher risk meaning worse score. This causes the flipping.

The `-f` flag was also flipped accordingly to serve the same purpose, although the value needs to be flipped by this user on the 0=> 100 scale.

I think we should have communicated this change better and I am sorry for the inconvenience. 

Hope it puts this issue in context

**Comment by slashben** [comment]
Also, we will bump the major version

**Comment by slashben** [comment]
@rotemamsa , note the request for bumping the major version!

**Comment by ZacHaque** [comment]
Are we talking about **f**=format or **t**=fail-threshold ?

**Comment by slashben** [comment]
> Are we talking about **f**=format or **t**=fail-threshold ?

fail-threshold

**Comment by rotemamsa** [comment]
version was bumped
