### ISSUE TITLE
Control C-0069 is skipped in a standard GKE cluster

### ISSUE THREAD

**Issue by avinashupadhya99** [armosec/kubescape#388]
The Control [C-0069](https://hub.armo.cloud/docs/c-0069) is skipped in a standard GKE cluster with the `--enable-host-scan` flag as well. 

![image](https://user-images.githubusercontent.com/52544819/153768824-65d1af0c-0e9d-439a-b61f-09154e8b5645.png)

**Comment by Bezbran** [comment]
Hi @avinashupadhya99 , thanks for pointing this out.

Looks like this is the same issue as #388, so we will investigate them both and will back to you.

**Comment by Bezbran** [comment]
Hi @avinashupadhya99, should be fixed in the new release [v2.0.148]https://github.com/armosec/kubescape/releases/tag/v2.0.148).
Just tested it on my own GKE cluster:
![image](https://user-images.githubusercontent.com/5871018/154906844-069ed1b4-0cb5-4d00-ac20-9cae3f999fd1.png)


Can you please check it and confirm it is OK?

**Comment by avinashupadhya99** [comment]
I can confirm that the control is being scanned now but I noticed that it says `Passed: 6` in the screenshot that you've attached. Is that for each node?
![image](https://user-images.githubusercontent.com/52544819/155180244-4642fc65-084b-4b59-b456-69577cef2a3f.png)
