### ISSUE TITLE
Privacy Violation

### ISSUE THREAD

**Issue by navzen2000** [armosec/kubescape#529]
All scan results are getting uploaded by default to 
{
  "accountID": "d9bb1de7-b577-4c66-8549-e5ff539b11ba"
}
This is getting created by default in ${USER_HOME}/.kubescape/config.json location

Whose account id is this?
This is an extreme privacy violation, please remove all uploaded scan information to above account,

Also, without the submit flag, tool is automatically uploading the results in the second iteration of run against same cluster.
Please fix this issue.

**Comment by dwertent** [comment]
Hi @navzen2000 ,

By default, Kubescape [does NOT submit the results](https://github.com/armosec/kubescape/blob/54020d317ed81697c7160698bd8a881909f4242f/core/core/initutils.go#L122).
If you scan once with the submit flag, kubescape will submit the results. If you wish not to submit results you can delete the cache (file and configMap -> `kubescape config delete`) or scan with the `keep-local` flag

Since this is open source you can confirm this behavior.
