### ISSUE TITLE
does online scanner require cluster admin?

### ISSUE THREAD

**Issue by fmtbkgiddiqq** [armosec/kubescape#55]
This is a really cool project! Great work.

I'm starting to learn about the project. I've tried scanning some test K8s clusters and found that the online scanner just crashes when it lacks permissions to perform certain functions or enumerate objects. 

Is there a feature or a plan to support operation under limited permission accounts, perhaps using input parameters? Error handling to continue during failures would also be helpful.

**Comment by dwertent** [comment]
Thank you for your warm feedback 😄, we are constantly improving Kubescape based on our roadmap and users feedback.

1. It's an interesting idea to use a flag- when set Kubescape will ignore errors. Regardlessly, I will like to further investigate that behavior- can you please share a scenario where the tool crashes because the lack of permissions? If you do not feel comfortable sharing publicly please feel free to contact me via email: [dwertent@armosec.io](dwertent@armosec.io)
2. You can scan kubernetes manifest files with Kubescape, simply run the command with the specified Kubernetes manifest you wish to scan. Please see the [docs for more examples](https://github.com/armosec/kubescape#examples)

Thank you;

**Comment by dwertent** [comment]
Closed since it did not reproduce and we got no response
