### ISSUE TITLE
Mutated release binaries

### ISSUE THREAD

**Issue by RothAndrew** [armosec/kubescape#98]
I'm checking SHASUMs as part of my process which pulls in the kubescape tool for testing of one of my clusters, and I've noticed they seem to be changing.

Would it be possible to update the release process to not mutate release binaries?

![image](https://user-images.githubusercontent.com/16000938/135477630-60109405-17cb-4a32-9291-820e4ba5dca1.png)

**Comment by dwertent** [comment]
@RothAndrew  I'm not sure I understand your request, when there is a new release by definition the release binary is different therefor the HASH will change accordingly.

Can you please clarify?

**Comment by RothAndrew** [comment]
The hash of the same file for the same release changed.

**Comment by dwertent** [comment]
@slashben Any thoughts?

**Comment by slashben** [comment]
@RothAndrew has a point, let's discuss this

**Comment by RothAndrew** [comment]
Bu downloading the file and running `sha256sum` on it. I'd prefer to pull from a published source though. Some projects publish the shasum as another release artifact next to the binary. That would be the preferred method.

**Comment by slashben** [comment]
@RothAndrew  will do today

**Comment by slashben** [comment]
@dwertent , I could not really sort this out. I did not find a cross platform way to calculate hash, neither how to upload multiple files to the release. Let's talk

**Comment by slashben** [comment]
@RothAndrew , I could create zip files containing both the hash and the binary itself.

See here: https://github.com/slashben/kubescape/releases/tag/v1.0.34

What do you think?

**Comment by RothAndrew** [comment]
That would be a big breaking change over the current release process. I'm fine with downloading the binary and calculating the hash.

**Comment by echoblag** [comment]
Hello @slashben , I'm a little late to this thread, but ran into the same problem of a mutated release and unexpected breakage. 

We run Kubescape through a CI pipeline. Since the agents are ephemeral a fresh copy of a specified version is downloaded. 

I am currently opting for the same solution as @RothAndrew and checksumming the binary.

I can see both sides of the coin in terms of the v1.0.134 approach of packaging the sha1 and binary in a zip file.

I was wondering if there is a longer term solution around this in the works? 

Thanks!

**Comment by slashben** [comment]
@echoblag , I am still a bit confused about the original issue. 

Are you saying that binary at `https://github.com/armosec/kubescape/releases/latest/download/kubescape-${osName}-latest` is mutating or a specific version is mutating, like `https://github.com/armosec/kubescape/releases/download/v1.0.130/kubescape-ubuntu-latest`?

**Comment by echoblag** [comment]
@slashben as best as I can tell the CI pipeline was consuming v1.0.130 and for no reason started failing because certain exception rules were no longer being read with no changes made to either the exceptions json file or the Kubescape version. 

The only time I have seen breaking changes is when switching between versions and figured it was worth mentioning as it might be a change to the v.1.0.130 artifact. This is speculative at best.

I have updated us to v1.0.135 and have added checksumming.

**Comment by slashben** [comment]
@echoblag , thanks. 

I assume it v1.0.130 has changed (out of nowhere) from your description

I want to go through with this till I understand what is happening, will keep you posted
